### ISSUE TITLE
Highlight > Border Size - option to be INSET, not OUTSIDE the frame

### ISSUE THREAD

**Issue by markonibomboni** [XiconQoo/Gladdy-TBC#1]
``Hi there,

I'm trying to create a look that is identical to Blizzard Raid Frames.
https://ibb.co/F86tBCN

Issues:
1.  In /gladdy ui, settings > Highlight > Border Size is set to 4, but the space it occupies is around the frame, unlike in Blizzard Raid Frames that has 'INSET' border, and it actually occupies space inside the frame itself. Is there any way to make this work?

2. Minor issue, on the screenshot you see where it say 'Gladdy - drag to move', it is actually larger than the frames themselves, and that left part is 'empty', and it makes Blizzard Raid Frames not clickable in that part.

Here is my Export:
`4XzRB1TKtRKd(jIP6)72xsagGQoaZsMtTNtvub8K4zswsIN12zHHl4zFv3sT)lXXgo5gIhB1sQLul9jzZc(IBxm)Ud3FF5m))82L57VjD1Qn7FyX75lMVmpF7Q8VTFwEXQSIxKVnVWVG0WdVl8ViHf()TQnRE(2hxJ0TmTSAwAXX8Gf4blWdwGhmppwbeHITHhfPl3KU947V)XBlY2LxCD((Q)(dGyZQc8AvXl3uME32SxSPy52Sf31Ogp0sfUwlsS8eT1yzsBIwS4(NPLNwTQk2S)RzvhXxu1E1E)Dx5VXJzvVjlDB1AqAVjBZdRbvYWc6AEv2UB2MwLHMNNV9BPpvEBAXdzv4Ad2V5RZ)2ZpuK(YSWF2iKBYlxm)JV91V5w)o8FVzv16RtxwLhS(Zxhf6TzFV6qr2I5Z2U5h)iTy1p)Yht3a)l8SwQ3nzflZ2xL(q2Iz1BVH80hzowdBSTHnxuTJENGwE7hUPLgHc07KMV5hzapfTdvIl81f5F7LBkYwwTjFF9gLmBbvQ0Rtv()uALo)FSCCnnfJwyxzwmpJCtZcEupJ4AoZEr4KJBhIrxLiqEDLp6AAStYSmZfsXsyxgg5K6lcJmQKldJ4m9fItAzI6IWiNqCzINek3qA0v6y4eYm43rzNuAmYlII54dQy)AmsBSxgNNqNWUmPdCC1qgPR4KrpPPE3imJz5xeTsBLxOtWAi17aBpinylEDvIzC2j1jjxg9IBVqBqU7YyYLIe3qMQFnoXndN)9kUPtqL3l4gNLqG1L5GJJBUm1y46)XLgQ6cNBX8xMxSP8gahrQhmuFCxaoM2i(808hBkREz29Ph2w5vbJfdQAeY8hl2amT6PfVxf0fHJozDsA4H0QCHuRhHpCMetaDoACkXW8bLLe8h8r5JrpMSKCHqnincIgo3oI(isOaKttdQpjAMCmDwRCJkllZn8(sI8XKytgJgHJnmnKF3K4gJpcMwngFKszYW(usFS2HnHK5roAuOlXnSroQWjd7ZrbPjmfNHeLIPg2vfnXIeXyhByQHfvDKJDyrHQJZOgn4s4eJzHDGkpMVuzoZMcpZaOdgn2IZe2HJJXDUqlSJ5ieq6IHLfLVqPsglYryfIrnHoyZpMd1PsoZ(cPjr6gZvyyJLnvluNjPJMsemQdvitedBC0OOSUXyJukyJLdukTJVVLJM2wPvYHPbdbnQXcsfc9Of(syJ6fKmXzs5epwDMqDsBySZucjg(jhrsvXbg0mFI3UB3H9z(L1cpfGhfXtXenO0Pr)GOka9bEu7H0upVK57YZRwdpm)BzfTgpYD1tHOSEAh9N(YQI)QfAK(6615f76QPDWAhG8TCBAzycCtEszXXZ1hheYG5vpbiLM)29vzf3NUm7tpF1QpSV8tVEB6Qvp9P3Ud2ALFcP9Zf5h2VkB1NVB7JDSxnZRzvr)Pd2Ft6Nz1yBYwR5xs)k)VhslI6xW)qk4egkz035NR2R2NT7Pa8Xw8G2KER3(9GHyz2oWZJdBchl2hZsxfww5Jzl9)Mf5drWFwMfgGhoYl)vRYkbzxMT9EqtYkpuqd2Q0hDVYVQWv4cUDnqYAWBgp1euV3L(DpN(FzfLWc)8U0)tEXN3FyhU7cJeShs5vfViTk7b4pZcQF52SSh7DY6(CiW27l98EJ)33ZLgwcgsvvSTS6W(PSgDIr6xtX(vtEjodkM1P4bIXwGXN7fwWxlNc1aSKquw5Y0kiQAARbADXVMvBk9MT9vtzrgFN9(fTCsuZvHIw3NLwmf6fCEyBuaPJMc9ANYroIFHLiclj7rFsoiKFsRkbx1QI0hGi57kYsHG9jSqfzKpKofQ1jw0EvKL9JSQI0jfcRDsLFvB29iCNj5yQdhFA5289tYey4bDlODP7YGCLBZ6DES5EHSD)9zQlu(QgXTU)u5VZRclpq07jbLrNspHjhupODkZAiFwy6GDEPd)g5D7ux4Uu8LoemD1LjI3kPV4q1akFxNST(1HuV4B3SlluDmfSO)XRU(wFWvRxMsZBjOFbxiSy5xZwfFjjWcDmat3mpaCBI1FbKoaqq7VJdal6VH0aTibxy9WuHF9D2pZJc0ewPibA2WtF8xaco3Frctgi0F20fyqGFHUk8RdoWgwGnbVHMldKrphHf7LxuGEeU()MffucpOycMf1eghVqQqg5ri5)vlqozSohYbPcjWpDHzr0F(7WdeYnAEypiCwKvGYHph)Zq77EojiL0irLsQybRNlreyqOr2WMWQcIYfLTg6NM2NmdjBCBOmkuz0AlQf6KKaTkoPWi2z4cTl8aJJ4LF6WWfwgzdb3z4cjy2XTSWeOiaMninUe1ubkur0CRLrRkkkeuQFPo0khMfsyjoCtRf4V4KlMfAe1s3GHxKO4ixDOL0ZD0Ea6fErscUhayYwCrsk20GgDHrAP9IaVrInSuD09bbZiHg8clUqSJn4cfliC4POKmuiih2i1bZbwAGSxijoDqO6yKIqIc3PXvaHqORWI(cYJHpfS2HvdfbXvB50zJOrwGeAzOrGJ33APFWJmqR)yablHmA2ekuxrxWnbkKmoUhXoIrwAO4mogmlusIn45eOPxmiMoWd5gOfiOJv(gNNrDLfeVGyaQFHjLmJAq0F7e60dToGA6al3f2(gmg0YjJI0eEUKtH1WHeussjzBrfYYPqfIpCHQ2Geo3vf6wjMLL1kD6KBuyvr36sT7(PDjJeS)HJFp7ek3MoO(5xM5rRgFWXLK6xPB6q0V2JcB12a6AaZ)EqDoSVYRpOskapjvXJai)qr(3(ZhRr17zYhHcB(BqLzM)yAXxBvwzvXVrTWxVnVSmk6NVS6q62GiiRvlXnXgtAkB)qhN4vQZ3Vx7gzJ3RFZzE)yVgEVjVakAUP63yR3bgqWi3S)Bp0(MoPilr7pzHOQcEnV2wcqD(Jn7j6dXlD8qD(EciweOQ92ABUheG)4YQtCCya7oPB1nS)mR84a2xCOOm7e8j2oRPUD2b(KqqBHRgA4)uZoDulEiOXEEQxns9X7jgkwf(iuAqA22P2EWg(5XOfxXnW)QzkMXTy(3xCTtBuqEFgdsmB9fQU)zq6r8f3eaOD(VReEtmEF3WnRFQCdK4ASblu5B3EwJr53WAtNVVlVQkF37adYM9TaTF0N4YSpC7TF4DTFCBK(T9btyBhpU69Un5PB7voIjxB0sfGvZc)it0q5o8JxkY4RDqnqO)zLwPbmbasOWZjHnBuNc7ejQMy0uyZJq9fOTOogsZAn3Qo2XOj48wlEt9StKARv7ud95w5pGSnlf24NV8z)yYZ)vkv)5q1UCQQPu9iFtwXc69Qdyr95kjnut6Jh6QGxKYhCYML(RbIeNyHMo(7OzMA4AwSDlaUhcHr4rSfWkPfecgedMdbGcXOuFdUeSBkteqAS7hlUsrc2gf3qnbieewFarnYBeljaH1qO1WgoS4cruHwccnXDgIEe0guDbeCi8xQHcn2jLwIi(GEYiiFooboxzrwznuhukReLGJq1Jq8GJJKwRIAnIXfwiIDgTyAb2Tb06dUIWC09CiHjqLb7tbmLiCuKEHYrOvH(xcgcLH0qYwl5guv1cSHdbxBeOSeuVzG1g7sYWXDoyePwAui(AH0gbARerG2OXYNVHAHg7ltyDieC8Lx4P1H9HdLiC1B)WfgQJaYmYrEBWEVQAvEV3iuADsfk2LL2RWmf)6JMBkn)yNJgDqh0EQlD(6uBn4KvfV)W2Tti34JrqxNy8oVl9Hnlpfgc)3(qqvfiUocGRxH6cUNkG9E)0PorknIvuQGJXT3g(7eYBJavg6tN91hYklZctTMe4jHMnH83iSPN2NUBZsK8zTE)hOxaoFt5HEF6USwUQJleQ1C4yJXWeqVPs4WpuOl8fYDne3bnrj1AOlph0ApvIShqqVqNqxuTRAuNUTrHLSEvkACdhbQjFtz((tgdB6312emNDJHBhXCCJENpIMK7Bs3E)eKBt9MUwH29Pmb20Q5YMZ9RkAJMkYXteH3swnRULJTDm66(Fx2ABhAjS1Iwu6d(A1zd)yDjumeFj7HmZ0aEK8eCMH430J)cMJOjoKP6Hl5NrcsSchwxC6ahviKlIJmm8Xt4VOE2smCKeq5wgnvlhnqkjrI0jT0QJtKKt1QIJKKZCjunwoDrIMMhOIgcjChQWrCkvolvKLPQvtA0OyTr8lsYFJWNuuqPsyDNaj3Iprk0QUL5QlKghweuGIM1RWwp)Mi6dlvWZHtdeCaKvwj5XkFKKIJbck6tZHrrZHryC0GBQltQ4KHwehRNm6iTjcQMwSozSCRJW0upYX66KgvCWMgk0rsgrQgU0OXATcJHgWAy6vWzMYQ0QdL3fpvhpQyx09d5)xQ)NJBY3pjL5(345SUht(v4k1vv8uZrVL8MJYRhot1azKX6v)1jsu0)Tf0Uf8jLc8FDiTO6m06XM3PDNwiMBEP51106mhe0sgZb1HU(6DTzlWa8fK0(vxxpgi61P0VnJ4oVtYuK26B9mURh2IJ)4gALG3051sneQIGXeQ)QfqT3eM0WGdHI6wq7HYPb31D9BFPUk7P(pMutnhCB(89lxdQt8qWI(Fuf)srUDpp0Zh36LU3)TVD(cW0Jrj(ZVClStQ284p)sqAGPzX)))3a)wx`

**Comment by XiconQoo** [comment]
Thanks for the report. Looking in to it.
Also: Neat idea to make it look like the Blizzard raid frames =)

**Comment by XiconQoo** [comment]
Coming with v1.08-Beta
