### ISSUE TITLE
[Version: 1.19-Beta]: I got these errors after game start, used Invisibility before gate open

### ISSUE THREAD

**Issue by stephanelol** [XiconQoo/Gladdy-TBC#12]
4x Gladdy\Modules\Racial.lua:180: attempt to index field '?' (a nil value)
[string "@Gladdy\Modules\Racial.lua"]:180: in function '?'
[string "@Gladdy\Gladdy-4.lua"]:130: in function 'Call'
[string "@Gladdy\Gladdy-4.lua"]:135: in function 'SendMessage'
[string "@Gladdy\EventListener.lua"]:58: in function 'SpotEnemy'
[string "@Gladdy\EventListener.lua"]:142: in function '?'
[string "@Gladdy\EventListener.lua"]:25: in function <Gladdy\EventListener.lua:24

4x Gladdy\EventListener.lua:67: Usage: UnitIsUnit("unit", "otherUnit")
[string "=[C]:"]: ?
[string "@Gladdy\EventListener.lua"]:67: in function 'SpotEnemy'
[string "@Gladdy\Modules\Healthbar.lua"]:127: in function <Gladdy\Modules\Healthbar.lua:97>

**Comment by XiconQoo** [comment]
thanks, looking into it
