### ISSUE TITLE
Controlling Text on Individual Modules

### ISSUE THREAD

**Issue by ManneN1** [XiconQoo/Gladdy-TBC#14]
Hello,

I'd like to be able to:
- Turn countdown text on and off on the various modules individually of one another.
- Choose timer format for each module individually of one another.

E.g: No countdown text on DRs/Trinket/Racials/Buffs&Debuffs, but have countdown text on Auras and Cooldowns. All controlled individually. 

Maybe I've misunderstood something and this functionality already exists - but I don't think so.

**Comment by XiconQoo** [comment]
Hi,

thanks for contacting this way. It's a lot easier than through curseforge. I will add this functionality. There are indeed some codesmells laying around to have this feature. Theoretically you could achive that with each modules Font-Color setting, setting the alpha to 0. Unfortunately, that does not work for all right now.

DR - works there
Cooldown - works
BuffsDebuffs - does not work
Trinket & Racial - font color setting missing

Gonna update Gladdy here. Thanks

**Comment by XiconQoo** [comment]
I will add an option to the relative Cooldown options of each module, where you can edit the alpha of the cooldown numbers (from 1 to 0)

**Comment by XiconQoo** [comment]
fixed with v1.22-Release
- added cooldown number alpha configuration for all modules
