### ISSUE TITLE
[Enhancement] DR Level Text Indication

### ISSUE THREAD

**Issue by ManneN1** [XiconQoo/Gladdy-TBC#17]
See: https://github.com/XiconQoo/Gladdy-TBC/pull/15 for details.

Since the ticket was closed for workflow reasons I'm re-opening it as an issue ticket instead.

Do you have an ETA?

Thanks in advance!

Best Regards,
ManneN

**Comment by XiconQoo** [comment]
I did not forget you. I am added it to my develop version already. Gonna be out soon. Currently testing the latest develop version.

**Comment by ManneN1** [comment]
How come you closed this? 

It hasnt been implemented afaik.

**Comment by XiconQoo** [comment]
I closed it for me as I have implemented on my dev version, which I plan to release this weekend

**Comment by XiconQoo** [comment]
Will be fixed with v2.00
