### ISSUE TITLE
Move Auras and detach from Class Icon

### ISSUE THREAD

**Issue by markonibomboni** [XiconQoo/Gladdy-TBC#20]
Hi there,

First of all, thank you very much for previous enhancement to make Gladdy look more like Blizzzard Raid Frames.

I have an additional feature request:
- Option to detach Auras from Class Icon and move to middle of the frame
- (and / or ) Option to disable Class Icon

Screenshot:
https://ibb.co/khfhMJP

(on the raid frames the icon in the middle is from Lose Control addon)

**Comment by XiconQoo** [comment]
Hey, thanks for the feedback. Gonna take a look and see when I can do it

**Comment by XiconQoo** [comment]
Will be implemented with v2.00

**Comment by markonibomboni** [comment]
You are awesome <3
