### ISSUE TITLE
grow up set position not working correctly

### ISSUE THREAD

**Issue by XiconQoo** [XiconQoo/Gladdy-TBC#29]
Anyone have any thoughts on why the location of my gladdy frame gets reset upon entering an arena and/or locking the frame? Only happens when I have grow set to "up" versus the default setting of down.

**Comment by XyzKangUI** [comment]
Check discord

**Comment by XyzKangUI** [comment]
I pmed you

**Comment by XiconQoo** [comment]
Will be fixed with v2.00
