### ISSUE TITLE
Error after Arena ends - TBC Gladdy

### ISSUE THREAD

**Issue by telias82** [XiconQoo/Gladdy-TBC#39]
Message: Interface\AddOns\Gladdy\Modules\Cooldowns.lua:466: attempt to index local 'icon' (a nil value)
Time: Sat Feb 19 19:12:10 2022
Count: 1
Stack: Interface\AddOns\Gladdy\Modules\Cooldowns.lua:466: attempt to index local 'icon' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Gladdy\Modules\Cooldowns.lua"]:466: in function UpdateCooldowns'
[string "@Interface\AddOns\Gladdy\Modules\Cooldowns.lua"]:271: in function ?'
[string "@Interface\AddOns\Gladdy\Gladdy.lua"]:174: in function Call'
[string "@Interface\AddOns\Gladdy\Gladdy.lua"]:179: in function SendMessage'
[string "@Interface\AddOns\Gladdy\EventListener.lua"]:73: in function SpotEnemy'
[string "@Interface\AddOns\Gladdy\EventListener.lua"]:41: in function ?'
[string "@Interface\AddOns\Gladdy\Gladdy.lua"]:174: in function Call'
[string "@Interface\AddOns\Gladdy\Gladdy.lua"]:179: in function SendMessage'
[string "@Interface\AddOns\Gladdy\Gladdy.lua"]:528: in function JoinedArena'
[string "@Interface\AddOns\Gladdy\Gladdy.lua"]:423: in function ?'
[string "@Interface\AddOns\Gladdy\Gladdy.lua"]:120: in function <Interface\AddOns\Gladdy\Gladdy.lua:106>

**Comment by XiconQoo** [comment]
will be fixed next version
