### ISSUE TITLE
Feature Request: Stealth / Vanish / Shadowmeld alpha scale on Gladdy

### ISSUE THREAD

**Issue by Moki182** [XiconQoo/Gladdy-TBC#43]
Hi

RMO here.

Feature Request:
I wanna see when the enemy Re-Stealthed / Vanished / Shadowmelded by lowering the alpha of the actual Gladdy HP and Mana frame by 0.2 for the duration. (or possible an alpha scale option for it)

![image](https://user-images.githubusercontent.com/84582380/155796329-2f1b3d22-5911-4d35-bae6-bd1fc9df33d0.png)

**Comment by XiconQoo** [comment]
the frames is grayed out for when the unit is stealthed atm

**Comment by Moki182** [comment]
> the frames is grayed out for when the unit is stealthed atm

Yeah I see it, but could you do this "lowering alpha" thing?
(also for Feign Death)

**Comment by XiconQoo** [comment]
added with v2.11-Release
