### ISSUE TITLE
Add Bestial Wrath as an aura on class icon

### ISSUE THREAD

**Issue by Simonm-l** [XiconQoo/Gladdy-TBC#47]

**Comment by XiconQoo** [comment]
![image](https://user-images.githubusercontent.com/13347591/167750451-96760734-69b0-4b59-8077-d8bccbaed995.png)

Won't add Bestial Wrath, because the Hunter get's the buff The Beast Within - > https://tbc.wowhead.com/spell=34471/the-beast-within

**Comment by XiconQoo** [comment]
I added the right buff id for The Beast Within now
