### ISSUE TITLE
Original author statement

### ISSUE THREAD

**Issue by miraage** [XiconQoo/Gladdy-TBC#5]
Hi. I've been looking for an arena addon for tbc classic and stumbled upon Gladdy.
I was quite suprised to see Schaka as original author. He took Gladdy long years ago when I stopped supporting it.

I was inspired by Gladius and tried to make something similar for TBC private servers. So I took ideas from Gladius and Proximo.
Here my repo https://github.com/miraage/gladdy, which Schaka forked at some point https://github.com/Schaka/gladdy

Part of me would like to be mentioned, another part thinks it doesnt matter much.

Off-topic: if you need some help understanding the codebase and maybe fix a thing or two - ping me on Discord osher#5008

**Comment by XiconQoo** [comment]
Hey Miraage,

sure thing, I will of course mention you! Sorry, if I passed a line here. Thank you for reaching out and thank you for the great work you did with Gladdy! I was not aware, that you are the original author. Great stuff =)

I fixed the readme and added you and your repo as the source for this edit.

I sent you a discord friend request.

Best, Knall
