### ISSUE TITLE
TotemPlates causes ElvUI nameplates to not show

### ISSUE THREAD

**Issue by XiconQoo** [XiconQoo/Gladdy-TBC#53]
> With update 2.11-Release a new bug has been introduced where Nameplates are not showing for certain mobs and other players when using ElvUI Nameplates and Gladdy. From testing and other people reporting same issue in the ElvUI support discord channel, we've found that Gladdy TotemPlates is the cause of issue here. When disabling TotemPlates the issue is gone and all ElvUI Nameplates are shown correctly.
> Could you verify @DnB_Junkee? :)

**Comment by FlexMBL** [comment]
@XiconQoo Is there a plan to fix this bug? It's still very recreateable and several people in the ElvUI discord has reported this issue. Looking forward to use the Totem Plates feature together with my ElvUI Nameplates when this gets fixed :)

**Comment by XiconQoo** [comment]
@FlexMBL The problem is, I can't recreate it at all. I am mostly on a PTR or Beta server running the latest ElvUI.

Can you give any hints how to recreate it?

**Comment by XiconQoo** [comment]
@FlexMBL I presumambly fixed it in the dedicated Addon TotemPlates](https://www.curseforge.com/wow/addons/totemplates/files/3923238). Please give it a try. You need to disable TotemPlates and TotemPulse in Gladdy.
