### ISSUE TITLE
Glow not fadding anymore on WeakAuras when using last version of Gladdy

### ISSUE THREAD

**Issue by mrbuds** [XiconQoo/Gladdy-TBC#59]
Hello, i'm a contributor of WeakAuras, we had a report today from a user who's glows would not fade when using WeakAuras together with last version of Gladdy

We identified the cause to be this commit <https://github.com/XiconQoo/Gladdy-TBC/commit/d385692cdcb7399e794003807c61bd6f19cbdcac>

I have not research exactly what is wrong in this change, but if you want to fork the lib you should change it's name to avoid breaking other addons, or submit a pull request upstream at https://github.com/Stanzilla/LibCustomGlow

**Comment by XiconQoo** [comment]
Hey @mrbuds, thanks for the reach out. A user reported that to me as well.
You are right. That commit is causing it and I reverted it. I actually didn't want to include it at all. Must have overseen it. 86fcff8ea83296ab47e9f3f53ff8638331f8172a reverts it with Gladdy v.2.22-Release.
