### ISSUE TITLE
I wanna activate the Gladdy-TBC in game

### ISSUE THREAD

**Issue by Junon2x** [XiconQoo/Gladdy-TBC#6]
Please help me~!
I want use this addon in game.
I had installed and tested (/gladdy ui  /gladdy test). It was good.
But the addon is not activated in arena.
I don't know why.

Next items are my addons list. Please let me know any crash list.

Atlas (Battlegrounds, Burningcrusade, ClassicWow, DungeonLos)
AtlasLootClassic
AtlasQuest
Auctionator
Bagnon
Bigwigs
Capping
DBM
Details
dgks (DG Kill Shot)
Dominos
ExtendedCharacterStats
FindParty
GearScoreLite
GTFO
Itemrack
LittleWigs
Mapster
MoosiAlert
NameplateCooldowns
Omnibar
OmniCC
OmniCD
Plater
Prat-3.0
Questie
SexyMap
SilverEyes
ThreatClassic2
TitanClassic
TomTom
TrinketMenu
VendorPrice
WeakAuras
ZPerl

**Comment by XiconQoo** [comment]
Known Conflicts:
dG Killshot Classic

Solution: This is caused by dG killshot classic. It overwrites a Blizzard API function "IsActiveBattlefieldArena()". Delete lines 43-46 in dgks_classic.lua

**Comment by Junon2x** [comment]
Oh Thank you for your kindness~
