### ISSUE TITLE
Gladdy - OmniCC support

### ISSUE THREAD

**Issue by Zkalf** [XiconQoo/Gladdy-TBC#8]
**Suggestion**

Add OmniCC support or create an option to modify the current one.
Personally I do not enjoy decimals on cooldown text.

The addon is amazing btw, keep up the good work.

**Comment by XiconQoo** [comment]
I wont add OmniCC support, as I like to have control over the numbers myself.
I will add an option to General -> Cooldown General -> Timer Format, where you will be able to change the format from miliseconds to seconds
