### ISSUE TITLE
DR timer not accurate?

### ISSUE THREAD

**Issue by stobias123** [XiconQoo/Gladdy-TBC#9]
Sometimes DR timer shows finished in arena, but the spell is still diminished... \

Could there be some kind of latency or other reason for it showing DR timer complete but the spell is still diminished.?

**Comment by vendethiel** [comment]
DR timers are dynamic

**Comment by miraage** [comment]
DR timers are dynamic, 15-20 seconds.

**Comment by XiconQoo** [comment]
Won't fix for now. I have not even started to develop anything to estimate the dynamic part.

**Comment by miraage** [comment]
@XiconQoo maybe add an option for a user to choose DR timer? I.e. tell users "hey DR is random, you can choose what you feel okay", and add a slider `min=15,max=20,step=0.5`, with the default value of 18?

**Comment by stobias123** [comment]
Ahh dang i didn't know this! Thanks for the response!

**Comment by XiconQoo** [comment]
@miraage yeah, will do.
